apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistante-dermatologue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistante-dermatologue
  template:
    metadata:
      labels:
        app: assistante-dermatologue
    spec:
      containers:
      - name: app
        image: elmansouri01/assistante-dermatologue:latest
        env:
        - name: _JAVA_OPTIONS
          value: "-Xmx512m -Xms256m"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod,api-docs"
        - name: MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED
          value: "true"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb-service:27017/assistante-dermatologue"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: assistante-dermatologue-service
spec:
  selector:
    app: assistante-dermatologue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.2
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymodel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymodel
  template:
    metadata:
      labels:
        app: mymodel
    spec:
      containers:
      - name: mymodel
        image: elbahjacharafeddine/myflaskapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mymodel-service
spec:
  selector:
    app: mymodel
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
